### ISSUE TITLE
Epic Review

### ISSUE THREAD

**Issue by jarrah42** [nova-model/nova-trame#19]
In GitLab by @evilkermit on Sep 6, 2024, 15:44 EDT

## Description

This is the last issue in the epic `Create a generic UI library for Trame apps`. Each epic must contain such an issue. An epic owner and a reviewer should work on it when the epic is ready.

--------------------------------------------------------------------------------

### Checklist

- [x] **All Epic Issues**:
    - All issues are finished 
    - All merge requests are approved 
    - All merge requests are merged 
    - If this was a repository to deploy or build something, make sure that happened

- [x] **Documentation**: 
  - Make sure that appropriate documentation related to this epic was created. 

- [x] **Acceptance Criteria**: 
  - Make sure that the epic satisfy the acceptance criteria (should be in the epic description)
   
- [x] **Tests**:
  - Make sure that all tests (automatic and manual) run successfully

### Success?

- [x] Add someone else as issue assignee review it (there will be no merge request for this issue since there
sholud be no code changes).

### Checklist

Please confirm that you reviewed the following and agreed that this is done.

- [x] **All Epic Issues**
- [x] **Documentation**
- [x] **Acceptance Criteria**
- [x] **Tests**:

### Success?
- [x] Approve the issue (in a comment) and let developer close it and close the epic.

*Migrated from GitLab: https://code.ornl.gov/ndip/public-packages/nova-trame/-/issues/18*

**Comment by jarrah42** [comment]
In GitLab by @evilkermit on Sep 6, 2024, 15:44 EDT

added to epic ndip&165

**Comment by jarrah42** [comment]
In GitLab by @evilkermit on Sep 24, 2024, 14:28 EDT

marked the checklist item ****Acceptance Criteria**:** as completed

**Comment by jarrah42** [comment]
In GitLab by @evilkermit on Sep 24, 2024, 14:40 EDT

@jarrah42 Sergey wanted me to assign this to you so that you can take a look at the state of our UI package (https://code.ornl.gov/ndip/public-packages/trame-facade). Now that we have automated testing as of early this afternoon, the package is "complete" in that it's installable, in use in both the SANS & TOPAZ GUIs, has documentation for usage, and has a good starting point for unit tests.

If you want to see the look and feel of things, you can run the widget gallery using the instructions here: https://code.ornl.gov/ndip/public-packages/trame-facade#example-application. If you need this to be hosted somewhere in order to view it, let me know and I'll discuss with Sergey.

**Comment by jarrah42** [comment]
marked the checklist item ****All Epic Issues**** as completed

**Comment by jarrah42** [comment]
marked the checklist item ****Documentation**** as completed

**Comment by jarrah42** [comment]
No, you're good to go
