### ISSUE TITLE
Epic Review

### ISSUE THREAD

**Issue by jarrah42** [nova-model/nova-trame#30]
In GitLab by @evilkermit on Oct 11, 2024, 12:39 EDT

## Description

This is a last issue in the epic `trame-facade Improvements`. Each epic must contain such an issue. An epic owner and 
a reviewer should work on it when the epic is ready.

--------------------------------------------------------------------------------

### Checklist

- [x] **All Epic Issues**:
    - All issues are finished 
    - All merge requests are approved 
    - All merge requests are merged 
    - If this was a repository to deploy or build something, make sure that happened

- [x] **Documentation**: 
  - Make sure that appropriate documentation related to this epic was created. 

- [x] **Acceptance Criteria**: 
  - Make sure that the epic satisfy the acceptance criteria (should be in the epic description)
   
- [x] **Tests**:
  - Make sure that all tests (automatic and manual) run successfully

### Success?

- [x] Add someone else as issue assignee review it (there will be no merge request for this issue since there
sholud be no code changes).

### Checklist

Please confirm that you reviewed the following and agreed that this is done.

- [x] **All Epic Issues**
- [x] **Documentation**
- [x] **Acceptance Criteria**
- [x] **Tests**:

### Success?
- [ ] Approve the issue (in a comment) and let developer close it and close the epic.

*Migrated from GitLab: https://code.ornl.gov/ndip/public-packages/nova-trame/-/issues/29*

**Comment by jarrah42** [comment]
In GitLab by @evilkermit on Oct 11, 2024, 12:39 EDT

added to epic ndip&180

**Comment by jarrah42** [comment]
In GitLab by @evilkermit on Oct 16, 2024, 13:58 EDT

marked the checklist item ****Tests**:** as completed

**Comment by jarrah42** [comment]
In GitLab by @evilkermit on Oct 16, 2024, 13:58 EDT

marked the checklist item **Add someone else as issue assignee review it (there will be no merge request for this issue since there** as completed

**Comment by jarrah42** [comment]
In GitLab by @35y on Oct 18, 2024, 08:34 EDT

marked the checklist item ****All Epic Issues**** as completed

**Comment by jarrah42** [comment]
In GitLab by @35y on Oct 18, 2024, 08:34 EDT

marked the checklist item ****Tests**:** as completed
